Alias /glpi /home/felix/FENTECH PROJECTS/GLPI/glpi/public

<Directory /home/felix/FENTECH PROJECTS/GLPI/glpi/public>
    Options -Indexes +FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>
