global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'glpi-frontend'
    static_configs:
      - targets: ['frontend:80']
    metrics_path: '/backend/metrics'
    scrape_interval: 30s

  - job_name: 'glpi-backend'
    static_configs:
      - targets: ['glpi:80']
    metrics_path: '/apirest.php'
    scrape_interval: 60s

  - job_name: 'caddy'
    static_configs:
      - targets: ['caddy:2019']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
